# Generated by Django 4.2.16 on 2026-09-19 09:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposits', '0002_deposit_auto_close_deposit_end_date'),
        ('finance', '0003_transfers_budgets_tags_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Цель')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Нужно накопить')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('saved_manual', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Используется, если не выбран счёт или вклад.', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Уже накоплено (вручную)')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('done', 'Достигнута'), ('cancelled', 'Отменена')], default='active', max_length=10, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='finance.account', verbose_name='Копить на счёте')),
                ('deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='deposits.deposit', verbose_name='Копить на вкладе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'deadline', 'name'],
            },
        ),
    ]
