# Generated by Django 4.2.16 on 2026-09-19 09:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringtemplate',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='Первая операция будет создана не раньше этой даты.', verbose_name='Действует с'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.recurringtemplate', verbose_name='Регулярный шаблон'),
        ),
        migrations.AlterField(
            model_name='recurringtemplate',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='1–31. Если в месяце меньше дней — операция создаётся в последний день месяца.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День месяца'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_template__isnull', False)), fields=('recurring_template', 'date'), name='unique_recurring_transaction_per_date'),
        ),
    ]
