# Generated by Django 4.2.16 on 2026-09-19 09:42

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_recurring_start_date_and_tx_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_transfer',
            field=models.BooleanField(default=False, help_text='Операции с этой категорией не учитываются в доходах/расходах и P&L.', verbose_name='Техническая категория переводов'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Чек'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.CharField(blank=True, help_text='Через запятую: такси, работа, отпуск', max_length=255, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_pair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_counterpart', to='finance.transaction', verbose_name='Парная операция перевода'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Лимит в месяц')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('category', models.ForeignKey(limit_choices_to={'type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_budget_per_category'),
        ),
    ]
