# Generated by Django 4.2.16 on 2026-09-19 09:55

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0003_transfers_budgets_tags_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('kind', models.CharField(choices=[('loan', 'Кредит'), ('installment', 'Рассрочка'), ('credit_card', 'Кредитная карта'), ('personal', 'Займ у человека / человеку'), ('other', 'Другое')], default='loan', max_length=20, verbose_name='Тип')),
                ('direction', models.CharField(choices=[('owe', 'Я должен'), ('owed', 'Мне должны')], default='owe', max_length=5, verbose_name='Направление')),
                ('counterparty', models.CharField(blank=True, max_length=120, verbose_name='Контрагент (банк / человек)')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Начальная сумма')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Текущий остаток')),
                ('annual_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ставка, % годовых')),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ежемесячный платёж')),
                ('payment_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='День платежа')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата открытия')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок погашения')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Погашен')], default='active', max_length=10, verbose_name='Статус')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Дата погашения')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liabilities', to='finance.account', verbose_name='Счёт для платежей')),
                ('recurring_template', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liability', to='finance.recurringtemplate', verbose_name='Регулярный платёж')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Обязательство',
                'verbose_name_plural': 'Обязательства',
                'ordering': ['status', '-balance'],
            },
        ),
    ]
