# Generated by Django 4.2.16 on 2026-08-22 08:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Тело вклада')),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Годовая ставка, %')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('capitalization_type', models.CharField(choices=[('simple', 'Простой процент'), ('monthly_compound', 'Ежемесячная капитализация')], default='simple', max_length=20, verbose_name='Тип капитализации')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('closed', 'Закрыт')], default='active', max_length=10, verbose_name='Статус')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='finance.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
