# Generated by Django 4.2.16 on 2026-09-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='auto_close',
            field=models.BooleanField(default=True, verbose_name='Закрывать автоматически по сроку'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='end_date',
            field=models.DateField(blank=True, help_text='Срок вклада. При наступлении вклад закрывается автоматически, деньги возвращаются на счёт.', null=True, verbose_name='Дата окончания'),
        ),
    ]
