# Generated by Django 4.2.16 on 2026-08-22 08:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('acquisition_value', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость приобретения')),
                ('quantity_or_share', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Количество / доля')),
                ('acquisition_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата приобретения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.CreateModel(
            name='SecurityValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Оценка')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата оценки')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='securities.security')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='securityvaluation',
            constraint=models.UniqueConstraint(fields=('security', 'date'), name='unique_valuation_per_security_date'),
        ),
    ]
